name:                p
version:             0.1.0.0
github:              "msvbg/p"
license:             MIT
author:              "Martin Svanberg"
maintainer:          "martin@martinsvanberg.com"
copyright:           "2019 Martin Svanberg"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/msvbg/p>

dependencies:
- base >= 4.7

executables:
  p:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - entropy
    - aeson >= 1.4.3.0
    - optparse-applicative >= 0.14.3.0
    - Hclip >= 3.0.0.4
    - filepath >= 1.4.2.1
    - directory >= 1.3.3.0
    - mtl >= 2.2.2

tests:
  p-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N