flags:
  transformers-compat:
    five-three: true
  time-locale-compat:
    old-locale: false
packages:
- .
extra-deps:
- Hclip-3.0.0.4
- aeson-1.4.3.0
- ansi-terminal-0.9
- ansi-wl-pprint-0.6.8.2
- attoparsec-0.13.2.2
- base-compat-0.10.5
- colour-2.3.4
- dlist-0.8.0.6
- entropy-0.4.1.4
- hashable-1.2.7.0
- integer-logarithms-1.0.3
- optparse-applicative-0.14.3.0
- primitive-0.6.4.0
- random-1.1
- scientific-0.3.6.2
- strict-0.3.2
- tagged-0.8.6
- th-abstraction-0.3.1.0
- time-locale-compat-0.1.1.5
- transformers-compat-0.6.4
- unordered-containers-0.2.10.0
- uuid-types-1.0.3
- vector-0.12.0.3
resolver: ghc-8.6.5
